export const FETCH_DATA_START = 'FETCH_DATA_START'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL'

export const FETCH_ADD_DATA_START = 'FETCH_ADD_DATA_START'
export const FETCH_ADD_DATA_SUCCESS = 'FETCH_ADD_DATA_SUCCESS'
export const FETCH_ADD_DATA_FAIL = 'FETCH_ADD_DATA_FAIL'

export const SELECT_POST = 'SELECT_POST'

export const FETCH_POST_START = 'FETCH_POST_START'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL'