export const SET_INITIAL_REQUEST = 'SET_INITIAL_REQUEST'

export const FETCH_DATA_START = 'FETCH_DATA_START'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL'

export const SET_SORT_BY_PARAM = 'SET_SORT_BY_PARAM'
export const SET_ORDER_BY_PARAM = 'SET_ORDER_BY_PARAM'
export const SET_SEARCH_PARAM = 'SET_SEARCH_PARAM'

export const FETCH_ADD_DATA_START = 'FETCH_ADD_DATA_START'
export const FETCH_ADD_DATA_SUCCESS = 'FETCH_ADD_DATA_SUCCESS'
export const FETCH_ADD_DATA_FAIL = 'FETCH_ADD_DATA_FAIL'

export const SELECT_POST = 'SELECT_POST'

export const FETCH_POST_START = 'FETCH_POST_START'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL'

export const REFRESH_DATA = 'REFRESH_DATA'
